### PR TITLE
✨ Updating WebGuy -> AcceptanceTester, added some case to catch new actions

### PR DESCRIPTION
**Pull request by svpernova09**
This is my first stab at writing code like this, it's likely going to be a trial and error process. If we can get this published I'll be able to debug and test it  asap.

### CODE REVIEW

**Comment by svpernova09** [comment]
@allmyitjason Here's the first PR at updating to newer version of codeception

**Comment by sp0tteh** [comment]
Looks good, you can however test it locally (without publishing to firefox) by building the addon and adding it into firefox from your local drive.

**Comment by sp0tteh** [comment]
Looks like the firefox dev ecosystem has changed a fair bit since i last played around in it, but looks like you need to do the following:

- Download Firefox Developer Edition
- go to about:config and set 'xpinstall.signatures.required' to false
- go to about:addons and from the gear icon select "Install addon from file"
- Browse to and select the install.xpi file from the src directory

This should load the addon, haven't tested passed this point myself recently though.

**Comment by svpernova09** [comment]
Thanks will do. The local testing is what I couldn't sort out. This sounds good.

--
- Joe Ferguson
JoeFerguson.me
MemphisPHP.org

**Comment by svpernova09** [comment]
It seems we're barking up the wrong tree :/ as Selenium IDE is no longer being maintained. It's currently not working with Firefox Developer Edition (latest version)

From #selenium on Freenode:

```
08:19 <joepferguson> Anyone running into issues with Selenium IDE 2.9.1 & the latest Firefox Developer Edition? Seems to load, but unable to open any menu windows (open test, open test suite, etc)
<snip>
08:19 <WhereIsMySpoon> :ide
08:19 <selbot2> Selenium IDE is no longer being maintained. You can ask a question, but most people here will be unable to help you. Instead, consider using WebDriver - http://www.seleniumhq.org/projects/webdriver/
<snip>
08:22 <joepferguson> Thanks WhereIsMySpoon, that info would be awesome to have on the site :/
08:23 <joepferguson> Is there any guidance on how to convert / move / autmoate the process of my old Selenium IDE tests to another format?
<snip>
08:25 <WhereIsMySpoon> joepferguson: there’s probably a load of articles out there, but it boils down to: get someone who can program, get them your list of tests with test steps and expected outcomes and get them to code up your tests
08:25 <WhereIsMySpoon> there isn’t really a way to move your IDE tests to code and have good code
<snip>
08:26 <joepferguson> Yeah, that's what I'm finding. I found an addon that exported the tests into a format that got me 50% of the format I need them in, and I started hacking on it to get it the rest of the way, only to find out IDE isn't compatible with new versions of FF Dev so I have no way to easily test >.<
08:26 <joepferguson> So it sounds like my best bet is to write an app that will parse my HTML files and build new files in the format I need them in.
<snip>
08:27 <WhereIsMySpoon> joepferguson: it’s more effort to try and “export” the tests and hack them into code than rewrite from scratch
08:27 <WhereIsMySpoon> and we do recommend you code up your tests
```

**Pull request closed without merging**
